baseurl = "/"
languageCode = "en-us"
title = "Blue SMPP"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Haisum Bhatti"
	description = "Documentation and Feature overview of Blue SMPP."
	copyright = "All rights reserved to Haisum."

	# Repository
	# provider = "GitHub"
	# repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	version = ""
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue"
    	accent  = "white"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"


[social]
	twitter = "haisum"
	github  = "haisum"
	email   = "haisumbhatti@gmail.com"


[[menu.main]]
	name   = "Blue SMPP"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Features"
	url    = "features/"
	weight = 10

[[menu.main]]
	name   = "Demo"
	url    = "demo/"
	weight = 20

[[menu.main]]
	name   = "Usage"
	url    = "usage/"
	weight = 30

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40

[[menu.main]]
	name   = "Contact Us"
	url    = "contact/"
	weight = 50

[[menu.main]]
	name   = "Purchase"
	url    = "purchase/"
	weight = 60

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
